Blog:
    type: entity
    table: blog
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        author:
            type: string
            length: 255
            fixed: false
            nullable: true
        text:
            type: text
            nullable: true
        created:
            type: datetime
            nullable: true
        updated:
            type: datetime
            nullable: true
        nameFile:
            type: string
            length: 500
            fixed: false
            nullable: true
            column: name_file
        isPublish:
            type: boolean
            nullable: false
            column: is_publish
    manyToOne:
        techno:
            targetEntity: BlogTechno
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                techno_id:
                    referencedColumnName: id
            orphanRemoval: false
        type:
            targetEntity: BlogType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
